# -*- coding: utf-8 -*-
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented
# out serve to show the default.

import sys, os

centralconfdir = os.path.dirname(os.path.dirname(__file__))
print centralconfdir
centralconfdir = os.path.join(os.pardir, os.pardir, centralconfdir)
print centralconfdir
sys.path.append(centralconfdir)
    
import centralconf

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#sys.path.append(os.path.abspath('.'))

# -- General configuration -----------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be extensions
# coming with Sphinx (named 'sphinx.ext.*') or your custom ones.
extensions = centralconf.extensions

# Add any paths that contain templates here, relative to this directory.
templates_path = centralconf.templates_path

# The suffix of source filenames.
source_suffix = centralconf.source_suffix

# The encoding of source files.
#source_encoding = 'utf-8'

# The master toctree document.
master_doc = centralconf.master_doc

# General information about the project.
project = u'User Manual for Miro'
copyright = u'2010, Participatory Culture Foundation.  Released under a Creative Commons Attribution-Share Alike 3.0 license.'

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = '3.0.2'
# The full version, including alpha/beta/rc tags.
release = version

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#language = None

# List of documents that shouldn't be included in the build.
#unused_docs = []

# List of directories, relative to source directory, that shouldn't be searched
# for source files.
exclude_trees = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = centralconf.pygments_style


# -- Options for HTML output ---------------------------------------------------


# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None

# A shorter title for the navigation bar.  Default is the same as html_title.
#html_short_title = None

html_static_path = centralconf.html_static_path
html_show_sourcelink = centralconf.html_show_sourcelink


# Output file base name for HTML help builder.
htmlhelp_basename = centralconf.htmlhelp_basename

html_theme = centralconf.html_theme
html_theme_options = centralconf.html_theme_options
html_logo = centralconf.html_logo

# -- Options for LaTeX output --------------------------------------------------

latex_documents = centralconf.latex_documents


# Additional stuff for the LaTeX preamble.
latex_preamble = centralconf.latex_preamble

